Work on Github Actions Backup V2

diff --git a/.github/workflows/list-backups-v2.yaml b/.github/workflows/list-backups-v2.yaml
--- a/.github/workflows/list-backups-v2.yaml
+++ b/.github/workflows/list-backups-v2.yaml
@@ -78,12 +78,16 @@ jobs:
           echo "::endgroup::"
 
           
-          CMD_RESULTS=$(rclone lsf :s3:webbackup/oc-sites-bk --include "${PROJECT_NAME}-${SITE_NAME}_${ENVIRONMENT}_*_backup.tar*" --files-only --s3-provider Other --s3-access-key-id "webbkaki" --s3-secret-access-key "${{ secrets.BCGOV_S3_SECRET_ACCESS_KEY }}" --s3-endpoint "https://digital-gov.objectstore.gov.bc.ca"  --contimeout "15s" --retries 3 | sort | tail -n 20 )
+          CMD_RESULTS=$(rclone lsf :s3:webbackup/oc-sites-bk --include "${PROJECT_NAME}-${SITE_NAME}_${ENVIRONMENT}_*_backup.tar*" --files-only --s3-provider Other --s3-access-key-id "webbkaki" --s3-secret-access-key "${{ secrets.BCGOV_S3_SECRET_ACCESS_KEY }}" --s3-endpoint "https://digital-gov.objectstore.gov.bc.ca"  --contimeout "15s" --retries 3 | sort | tail -n 20 2>&1)
+          CMD_EXIT_CODE=$?
 
           echo "$CMD_RESULTS"
           
-          if [ -z "$CMD_RESULTS" ]; then
-              echo "::error::Unknown backup file name: ${CMD_RESULTS}"
+          if [[ $CMD_EXIT_CODE -eq 0 ]]; then
+            echo "Bucket check complete."
+
+          else
+              echo "::error::Error grabbing list: ${CMD_RESULTS}"
 
               exit 96
           fi 
