Digimod GH Actions - Move to using a different secret for each SSO project.

diff --git a/.github/workflows/reconfigure_sso.yaml b/.github/workflows/reconfigure_sso.yaml
--- a/.github/workflows/reconfigure_sso.yaml
+++ b/.github/workflows/reconfigure_sso.yaml
@@ -30,19 +30,28 @@ jobs:
     runs-on: ubuntu-22.04
     steps:
       - name: Prepare Keycloak
+        id: prepare-step
         run: |
           OC_PROJECT_NAME=${{ github.event.inputs.PROJECT-NAME }}
           
           if [ "$OC_PROJECT_NAME" == "digital" ];  then #legacy key name for digital
-            clientKeycloakSecretName="KEYCLOAK_TEST_CLIENT_SECRET"
+            CLIENT_KEYCLOAK_SECRET_NAME="KEYCLOAK_TEST_CLIENT_SECRET"
           else
-            clientKeycloakSecretName="KEYCLOAK_$OC_PROJECT_NAME_${{ github.event.inputs.SITE-NAME }}_TEST_CLIENT_SECRET"              
+            CLIENT_KEYCLOAK_SECRET_NAME="KEYCLOAK_$OC_PROJECT_NAME_${{ github.event.inputs.SITE-NAME }}_TEST_CLIENT_SECRET"              
           fi
 
-          echo "::set-output name=clientKeycloakSecretName::${clientKeycloakSecretName}";
+          echo "::set-output name=CLIENT_KEYCLOAK_SECRET_NAME::${CLIENT_KEYCLOAK_SECRET_NAME}";
+
+          echo "Secret Name"
+          echo "$CLIENT_KEYCLOAK_SECRET_NAME"
+          
+          if [ -z "${CLIENT_KEYCLOAK_SECRET_NAME}" ]; then
+            echo "Unable to determine keycloak secret name. Exiting."
+            exit 1
+          fi
 
     outputs:
-      clientKeycloakSecretName: ${{ steps.prepare-step.outputs.clientKeycloakSecretName }}
+      CLIENT_KEYCLOAK_SECRET_NAME: ${{ steps.prepare-step.outputs.CLIENT_KEYCLOAK_SECRET_NAME }}
 
   deploy:
     runs-on: ubuntu-22.04
@@ -60,7 +69,7 @@ jobs:
 
     - name: Rename Miniorange plugin variables and settings
       env:
-        CLIENT_KEYCLOAK_SECRET_NAME: ${{ needs.prepare.outputs.clientKeycloakSecretName }}
+        CLIENT_KEYCLOAK_SECRET_NAME: ${{ needs.prepare.outputs.CLIENT_KEYCLOAK_SECRET_NAME }}
       run: |
         ENVIRONMENT=${{ github.event.inputs.ENVIRONMENT }}
         echo "Deploying to the site $OC_SITE_NAME in $ENVIRONMENT"
@@ -104,7 +113,12 @@ jobs:
         ssoURI=''
 
         echo "Secret Name"
-        echo "${CLIENT_KEYCLOAK_SECRET_NAME}"
+        echo "$CLIENT_KEYCLOAK_SECRET_NAME"
+        
+        if [ -z "${CLIENT_KEYCLOAK_SECRET_NAME}" ]; then
+          echo "Unable to determine keycloak secret name. Exiting."
+          exit 1
+        fi
 
         case $OC_ENV in
           'dev')
